/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/BaseInfo.ls
 */
export class BaseInfoBase extends Laya.Scene {
    public listItem!: Laya.List;
}

