/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/HomeScene.ls
 */
export class HomeSceneBase extends Laya.Scene {
    public iconList!: Laya.List;
}

