/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/ScoreInfo.ls
 */
export class ScoreInfoBase extends Laya.Scene {
    public labToday!: Laya.Label;
    public labTotal!: Laya.Label;
    public listItem!: Laya.List;
}

