/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefabs/AlertDialog.lh
 */
export class AlertDialogBase extends Laya.Dialog {
    public labTitle!: Laya.Label;
    public labDesc!: Laya.Label;
}

